### ISSUE TITLE
Number of values an option take is incorrectly calculated when action=='callback' and positional_argument == TRUE

### ISSUE THREAD

**Issue by nh3** [trevorld/r-optparse#28]
https://github.com/trevorld/r-optparse/blob/6f4d9c04af8e0e30abd7a1f540acf8ee60d7360f/R/optparse.R#L630-L639

In the above code, line 634 should be
```
if (!option@action %in% c("store_true", "store_false")) { 
```

**Comment by trevorld** [comment]
@nh3  Thanks for the bug report!  Should be fixed now in the developmental version of optparse.

**Comment by nh3** [comment]
Thanks @trevorld for the quick fix. This is very comprehensive.
