### ISSUE TITLE
Metavar printing for options with action == 'callback'

### ISSUE THREAD

**Issue by nh3** [trevorld/r-optparse#29]
Similar to #28, metavar are only printed for options with action == 'store'.

https://github.com/trevorld/r-optparse/blob/0ea3ccac3ff2dada907e522d3340f2e4aa46f8f7/R/optparse.R#L327-L329

https://github.com/trevorld/r-optparse/blob/0ea3ccac3ff2dada907e522d3340f2e4aa46f8f7/R/optparse.R#L334-L336

**Comment by trevorld** [comment]
Thanks again for the bug report!  Should be fixed now in the developmental version of ``optparse``.
