### ISSUE TITLE
Short flag -co must only be a '-' and a single letter                                                             

### ISSUE THREAD

**Issue by zqsha** [trevorld/r-optparse#33]
Hi,

First, I successfully set up optparse in R in Linux system. When I employ this package, it said:
Error in make_option(c("-co", "--corin"), type = "character", default = "corin.txt",  :                             
  Short flag -co must only be a '-' and a single letter

Do you have any suggestions? Thanks.

**Comment by trevorld** [comment]
Short flag must only be a '-' and a **single** letter i.e. '-c' or '-o' is allowed but not '-co' (**two** letters is not a **single** letter).  Note that ``parse_args`` interprets ``-co`` as equivalent to ``-c -o`` and hence long "short" flags don't make sense.

However also note short flags are optional and you can have many long flags point to the same variable with the "dest" option. So one could have code like below if you really did not want to use ``-c`` and wanted ``--co`` (note double ``--``) to be an alias for ``--corin``:

```
p <- OptionParser()
p <- add_option(p, "--corin", type = "character", default = "corin.txt")
p <- add_option(p, "--co", dest = "corin")
```
