### ISSUE TITLE
?make_option should mention "callback" as a possible value for action

### ISSUE THREAD

**Issue by greg-minshall** [trevorld/r-optparse#35]
if you provide a callback function, but *don't* specify `action="callback"`, you get a warning.

and, the man page ?make_option (or ?add_option) doesn't mention `"callback"` as a possible value for the `action` parameter.

**Comment by trevorld** [comment]
> if you provide a callback function, but don't specify action="callback", you get a warning.

This seems to [match the behaviour of the API](https://docs.python.org/2/library/optparse.html#option-callbacks) I'm mimicking.  Not sure I want to change that.

> and, the man page ?make_option (or ?add_option) doesn't mention "callback" as a possible value for the action parameter.

I should improve the man page callback documentation.
