### ISSUE TITLE
Passing arguments with spaces?

### ISSUE THREAD

**Issue by gguyver** [trevorld/r-optparse#39]
Hi, is there any way to pass arguments with spaces?

I currently need to pass a filename and it keeps splitting it into separate arguments, which messes up parse_args().

If not, are there any plans to?

Thanks.

**Comment by trevorld** [comment]
I'll follow up in a couple of days when I have access to a computer.

**Comment by trevorld** [comment]
If you need spaces you should be able to enclose the argument within quotes although this maybe system specific.

```
$ cat optparse.R 
library("optparse")
parser <- OptionParser()
parser <- add_option(parser, "--file")
print(commandArgs(T))
print(parse_args(parser))

$ Rscript optparse.R --file="file name.txt"
[1] "--file=file name.txt"
$help
[1] FALSE

$file
[1] "file name.txt"
```
